### ISSUE TITLE
Add support for DeletedAt

### ISSUE THREAD

**Issue by fi0** [dizzyfool/genna#13]

**Comment by dizzyfool** [comment]
> _No description provided._

Could you please provide some additional info, what do you exactly want to be supported?

**Comment by fi0** [comment]
go-pg supports soft delete with
```
DeletedAt time.Time `pg:",soft_delete"` 
```

It would be nice if there's a flag for toggling the soft_delete field generation.

**Comment by dizzyfool** [comment]
Sorry for delay. Use `--soft-delete` param to specify necessary column e.g.
```
--soft-delete deletedAt
```
it will generate something like this:
```go
type User struct {
	DeletedAt pg.NullTime `sql:"deletedAt" pg:",soft_delete"`
}
```
