### ISSUE TITLE
Can not be used, pg revision changed the structure of several files

### ISSUE THREAD

**Issue by jkingben** [dizzyfool/genna#16]
Can not be used, pg revision changed the structure of several files

C:\Users\Dev1>go get github.com/dizzyfool/genna
# github.com/dizzyfool/genna/database
E:\Work\GO\package\src\github.com\dizzyfool\genna\database\database.go:24:7: event.Data undefined (type *pg.QueryEvent has no field or method Data)
E:\Work\GO\package\src\github.com\dizzyfool\genna\database\database.go:35:10: event.Data undefined (type *pg.QueryEvent has no field or method Data)
E:\Work\GO\package\src\github.com\dizzyfool\genna\database\database.go:36:20: event.Data undefined (type *pg.QueryEvent has no field or method Data)
E:\Work\GO\package\src\github.com\dizzyfool\genna\database\database.go:54:36: cannot use NewQueryLogger(logger) (type QueryLogger) as type pg.QueryHook in argument to client.baseDB.AddQueryHook:
        QueryLogger does not implement pg.QueryHook (wrong type for AfterQuery method)
                have AfterQuery(*pg.QueryEvent)
                want AfterQuery(context.Context, *pg.QueryEvent) (context.Context, error)

**Comment by dizzyfool** [comment]
Should be working now
