### ISSUE TITLE
UUID type not updating

### ISSUE THREAD

**Issue by jayco** [dizzyfool/genna#20]
Hi, amazing tool.

I am probably missing a config setting or just not using this right. I have auto generated models from my Postgres database. Everything works as expected retrieving models but when I go to update them I get an error `operator does not exist: uuid = text`.

I did some googling and found `https://github.com/go-pg/pg/issues/622`. Adding the type manually here as suggested worked.

I am using go-pg `v8.0.4` and pulled down the latest version of genna.

Is there away to have genna generate the UUID type?

**Comment by dizzyfool** [comment]
Thanks for the report. Should be working now, please update & check.

**Comment by jayco** [comment]
Looks like the breaking 8 -> 9beta change https://github.com/go-pg/pg/commit/0606f10e934f2531cc27b1a7114373cdf27dcdb3#diff-6824f41d082d8d1e355aae9838a40779R32 is giving me a broken build on 8.

```
go: finding github.com/dizzyfool/genna latest
# github.com/dizzyfool/genna/lib
../../../go/pkg/mod/github.com/dizzyfool/genna@v0.0.0-20190725082813-c9840c1604ca/lib/database.go:25:7: event.Stash undefined (type *pg.QueryEvent has no field or method Stash)
../../../go/pkg/mod/github.com/dizzyfool/genna@v0.0.0-20190725082813-c9840c1604ca/lib/database.go:26:7: event.Stash undefined (type *pg.QueryEvent has no field or method Stash)
../../../go/pkg/mod/github.com/dizzyfool/genna@v0.0.0-20190725082813-c9840c1604ca/lib/database.go:38:10: event.Stash undefined (type *pg.QueryEvent has no field or method Stash)
../../../go/pkg/mod/github.com/dizzyfool/genna@v0.0.0-20190725082813-c9840c1604ca/lib/database.go:39:20: event.Stash undefined (type *pg.QueryEvent has no field or method Stash)
../../../go/pkg/mod/github.com/dizzyfool/genna@v0.0.0-20190725082813-c9840c1604ca/lib/database.go:60:37: cannot use newQueryLogger(logger) (type queryLogger) as type pg.QueryHook in argument to client.baseDB.AddQueryHook:
        queryLogger does not implement pg.QueryHook (wrong type for AfterQuery method)
                have AfterQuery(context.Context, *pg.QueryEvent) (context.Context, error)
                want AfterQuery(*pg.QueryEvent)
```

**Comment by dizzyfool** [comment]
Really annoying that go-pg has breaking changes so frequently

**Comment by vmihailenco** [comment]
Agreed, but that is why it is called beta :/

**Comment by dizzyfool** [comment]
So, I decided to update go-pg dependancy to v9. I don't understand why go mod ignores go-pg version I specify in go.mod file and downloads v7 or v8.
