### ISSUE TITLE
JSONB to slice

### ISSUE THREAD

**Issue by fi0** [dizzyfool/genna#21]
How do I generate an Int slice or String slice instead of map[string]interface{} ?

**Comment by dizzyfool** [comment]
Unfortunately there is no way to do it right now, but I'm going to implement flag that will give user ability to override json types. Like this:
`--json=user.params:UserParams,*=[]string`

**Comment by dizzyfool** [comment]
Please check the new version of model generator. It should have `-j` param now. 
`-j users.params=UserParams,users.*=[]string`. 
You can use asterisk as wildcard, so 
`*=T`, will assign T type any json field 
`users.*=T`, will assign T type for every json field in users table
`users.params=T`, will assign T type for params field of users table
`*.params=T`, will assign T type for every field named params in any table
