### ISSUE TITLE
Please add cast UUID type for column

### ISSUE THREAD

**Issue by s-kravchuk-elama** [dizzyfool/genna#37]
Please add cast UUID type for column.
Example
```
CREATE TABLE test_table
(
    "test_uuid" uuid    NOT NULL,
    primary key (test_uuid)
);
```
TO 
```
type TestTable struct {
      tableName struct{} `pg:"test_table,alias:t,,discard_unknown_columns"`
      
      ID uuid.UUID `pg:"test_uuid,pk,type:uuid"`
}
```

**Comment by dizzyfool** [comment]
Which uuid package do you suggest to use?

**Comment by alfssobsd** [comment]
I prefer https://github.com/google/uuid

**Comment by alfssobsd** [comment]
https://github.com/dizzyfool/genna/pull/38 - but i didn't write test yet :(

**Comment by dizzyfool** [comment]
Did it with more universal approach, for further custom types support
Ref: [ed0dabf](https://github.com/dizzyfool/genna/commit/ed0dabff77a6a75eecc698c51c0ce524282d364f)
