### ISSUE TITLE
Duplicate fields when UNIQUE constraint is used.

### ISSUE THREAD

**Issue by wildsurfer** [dizzyfool/genna#4]
#3 PR brought new problem. Now fields with unique constraints are duplicated in some cases. 
<img width="708" alt="screen shot 2019-02-02 at 15 48 19" src="https://user-images.githubusercontent.com/1456389/52164935-270b9880-2702-11e9-8a67-3442b88138a7.png">

I'm trying to fix it but also want to cover this functionality with tests. 

Trying to run tests gives me:

```
test/model/users.go:4:2: cannot find package "github.com/dizzyfool/genna/test/geo" in any of:

	/usr/local/Cellar/go/1.9.2/libexec/src/github.com/dizzyfool/genna/test/geo (from $GOROOT)

	/Users/kuzma/Documents/Workspace/go/src/github.com/dizzyfool/genna/test/geo (from $GOPATH)

Process finished with exit code 1
```

**Comment by wildsurfer** [comment]
I've figured out how to deal with tests. nvm :)

**Comment by wildsurfer** [comment]
Ok. Here is more info. This problem happens only for composite constraints. Like this one:

```
CREATE TABLE contracts (
	id serial NOT NULL,
	contract_id int4 NOT NULL,
	employee_id int4 NOT NULL,
	CONSTRAINT contracts_fixed_employees_un UNIQUE (contract_id, employee_id)
);
```

**Comment by dizzyfool** [comment]
The best way to fix this I think - is to tune sql query which gets columns

**Comment by wildsurfer** [comment]
Yes. I'm working on this :) Will provide PR soon.

Also my previous message is wrong. Issue is not in composite constraint. issue is when there is UNIQUE constraint together with FOREIGN KEY

```
drop table if exists employees;

CREATE TABLE employees (
	id serial NOT NULL,
	CONSTRAINT employees_pk PRIMARY KEY (id)
);

drop table if exists contracts;

CREATE TABLE contracts (
	id serial NOT NULL,
	employee_id int4 NOT NULL,
	CONSTRAINT contracts__un UNIQUE (employee_id),
	CONSTRAINT contracts_employees_fk FOREIGN KEY (employee_id) REFERENCES employees(id)
);

```

**Comment by wildsurfer** [comment]
Problem fixed. PR is ready to be merged. But please review it anyway :)
